[package]
name = "tract-onnx"
version = "0.6.3"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/snipsco/tract"
keywords = [ "TensorFlow", "NeuralNetworks", "ONNX" ]
categories = [ "science" ]
autobenches = false
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
bytes = "0.5"
derive-new = "0.5"
error-chain = "0.12"
libmath = "0.2.1"
log = "0.4"
num-integer = "0.1"
prost = "0.6"
smallvec = "1"
tract-hir = "0.6.3"

[build-dependencies]
prost-build = "0.6"
